[linters]
disable = ["depguard", "testpackage", "lll", "gci", "cyclop"]
enable-all = true
fast = true

[[issues.exclude-rules]]
linters = ["gocyclo", "gocognit", "funlen", "nestif"]
path = "_test.go"
